/* Body file for function CAN_bus_mock
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "can_bus_mock.h"

#include <stdio.h>
#include <string.h>

#include <sys/socket.h>
#include <sys/types.h>
#include <sys/ioctl.h>
#include <net/if.h>
#include <linux/can.h>
#include <unistd.h>

#include <pthread.h>

static struct ifreq ifr;
static int can_socket = 0;
static struct sockaddr_can addr;
static pthread_t recv_thread;

static void* recv_thread_main(void* ignored)
{
    printf("can_bus_mock thread started\n");
    struct can_frame frame;
    asn1SccRaw_Can_Frame parameter;
    uint32_t* can_id_ptr = (uint32_t*)(parameter.arr);
    uint8_t* can_data = (uint8_t*)(parameter.arr + sizeof(uint32_t));
    int r = 0;
    while((r=read(can_socket, &frame, sizeof(struct can_frame))) >= 0)
    {
        if(r == sizeof(struct can_frame))
        {
            printf("can_bus_mock received a frame\n");
            *can_id_ptr = frame.can_id;
            memcpy(can_data, frame.data, 8);
            parameter.nCount = frame.len;
            can_bus_mock_RI_receive_can_frame(&parameter);
        }
        else
        {
            printf("can_bus_mock invalid read, %d\n", r);
        }
    }

    printf("can_bus_mock socket closed\n");

    return NULL;
}

void can_bus_mock_startup(void)
{
    can_socket = socket(PF_CAN, SOCK_RAW, CAN_RAW);
    strcpy(ifr.ifr_name, "vcan0");
    ioctl(can_socket, SIOCGIFINDEX, &ifr);

    addr.can_family = AF_CAN;
    addr.can_ifindex = ifr.ifr_ifindex;
    bind(can_socket, (struct sockaddr*)&addr, sizeof(addr));

    pthread_create(&recv_thread, NULL, &recv_thread_main, NULL);
}

void can_bus_mock_PI_send_can_frame
      (const asn1SccRaw_Can_Frame *IN_frame)

{
    uint32_t* can_id_ptr = (uint32_t*)IN_frame;
    struct can_frame frame;
    frame.can_id = *can_id_ptr;
    frame.len = IN_frame->nCount - sizeof(uint32_t);
    memcpy(frame.data, IN_frame->arr + sizeof(uint32_t), 8);
    int r = write(can_socket, &frame, sizeof(struct can_frame));
    if(r == sizeof(struct can_frame))
    {
        printf("can_bus_mock frame sent\n");
    }
    else
    {
        printf("can_bus_mock invalid result [%d] from write\n", r);
    }

}


