/* Body file for function time_provider_mock
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "time_provider_mock.h"
//#include <stdio.h>


void time_provider_mock_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[time_provider_mock] Startup");
}

void time_provider_mock_PI_get_current_elapsed_time(void)
{
   // Write your code here
}


