/* Body file for function tester
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "tester.h"
#include <stdio.h>

static const char *nmt_command_to_string(asn1SccCANopen_NMT_Command cmd) {
  switch (cmd) {
  case CANopen_NMT_Command_start:
    return "START";
  case CANopen_NMT_Command_stop:
    return "STOP";
  case CANopen_NMT_Command_enter_preop:
    return "ENTER_PREOP";
  case CANopen_NMT_Command_reset_node:
    return "RESET_NODE";
  case CANopen_NMT_Command_reset_comm:
    return "RESET_COMM";
  default:
    return "UNKNOWN";
  }
}

static const char *nmt_state_to_string(asn1SccCANopen_NMT_State state) {
  switch (state) {
  case CANopen_NMT_State_bootup:
    return "BOOTUP";
  case CANopen_NMT_State_stop:
    return "STOP";
  case CANopen_NMT_State_start:
    return "START";
  case CANopen_NMT_State_reset_node:
    return "RESET_NODE";
  case CANopen_NMT_State_reset_comm:
    return "RESET_COMM";
  case CANopen_NMT_State_preop:
    return "PREOP";
  default:
    return "UNKNOWN";
  }
}

void tester_startup(void) {
  // Write your initialisation code
  // You may call sporadic required interfaces and start timers
  // puts ("[tester] Startup");
}

void tester_PI_nmt_command_indicator(
    const asn1SccCANopen_NMT_Command *IN_command)

{
  printf("[tester] Received NMT command trigger: 0x%02X (%s)\n", *IN_command,
         nmt_command_to_string(*IN_command));
}

void tester_PI_nmt_state_indicator(
    const asn1SccCANopen_Unsigned8 *IN_nodeid,
    const asn1SccCANopen_NMT_State *IN_nodestate)

{
  printf("[tester] Received NMT state change trigger for node 0x%02lX: "
         "0x%02X (%s)\n",
         *IN_nodeid, *IN_nodestate, nmt_state_to_string(*IN_nodestate));
}
