/* Body file for function vcan
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "vcan.h"
#include "dataview-uniq.h"

#include <stdio.h>
#include <string.h>

#include <linux/can.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

#include <pthread.h>

static struct ifreq ifr;
static int can_socket = 0;
static struct sockaddr_can addr;
static pthread_t recv_thread;

static void *recv_thread_main(void *ignored) {
  (void)ignored;

  printf("[vcan] Receiver thread started\n");
  struct can_frame frame;
  int r = 0;

  while ((r = read(can_socket, &frame, sizeof(struct can_frame))) >= 0) {
    if (r == sizeof(struct can_frame)) {
      printf("[vcan] Received a frame, ID: 0x%X, length: %d bytes\n",
             frame.can_id, frame.len);

      // Convert can_frame into asn1SccCan_Frame
      asn1SccCan_Frame asn_frame;
      asn1SccCan_Frame_Initialize(&asn_frame);

      // Check if extended frame (bit 31 set in can_id)
      if (frame.can_id & CAN_EFF_FLAG) {
        // Extended ID (29 bits)
        asn_frame.id.kind = Can_Id_extended_id_PRESENT;
        asn_frame.id.u.extended_id = frame.can_id & CAN_EFF_MASK;
      } else {
        // Standard ID (11 bits)
        asn_frame.id.kind = Can_Id_standard_id_PRESENT;
        asn_frame.id.u.standard_id = frame.can_id & CAN_SFF_MASK;
      }

      // Copy data
      asn_frame.data.nCount = frame.len;
      if (frame.len > 8)
        asn_frame.data.nCount = 8; // Clamp to max size
      memcpy(asn_frame.data.arr, frame.data, asn_frame.data.nCount);

      // Call the required interface with the converted frame
      vcan_RI_receive_data(&asn_frame);

    } else {
      printf("[vcan] Invalid read, %d\n", r);
    }
  }

  printf("[vcan] Socket closed\n");

  return NULL;
}

void vcan_startup(void) {
  printf("[vcan] Starting up...\n");

  can_socket = socket(PF_CAN, SOCK_RAW, CAN_RAW);
  if (can_socket < 0) {
    printf("[vcan] Error: could not create socket\n");
    return;
  }

  strncpy(ifr.ifr_name, "vcan0", IFNAMSIZ - 1);
  ifr.ifr_name[IFNAMSIZ - 1] = '\0';
  if (ioctl(can_socket, SIOCGIFINDEX, &ifr) < 0) {
    printf("[vcan] Error: could not get interface index\n");
    close(can_socket);
    return;
  }

  addr.can_family = AF_CAN;
  addr.can_ifindex = ifr.ifr_ifindex;
  if (bind(can_socket, (struct sockaddr *)&addr, sizeof(addr)) != 0) {
    printf("[vcan] Error: could not bind the socket to the address, aborting "
           "startup!\n");
    close(can_socket);
    return;
  }

  if (pthread_create(&recv_thread, NULL, &recv_thread_main, NULL) != 0) {
    printf("[vcan] Error: could not create receiver thread\n");
    close(can_socket);
    return;
  }
}

void vcan_PI_transmit_data(const asn1SccCan_Frame *IN_frame) {
  if (IN_frame == NULL) {
    printf("[vcan] Error: NULL frame pointer\n");
    return;
  }

  if (can_socket <= 0) {
    printf("[vcan] Error: socket not initialized\n");
    return;
  }

  struct can_frame frame;
  memset(&frame, 0, sizeof(struct can_frame));

  // Convert from IN_frame to frame
  if (IN_frame->id.kind == Can_Id_extended_id_PRESENT) {
    // Extended ID (29 bits)
    frame.can_id = IN_frame->id.u.extended_id | CAN_EFF_FLAG;
  } else if (IN_frame->id.kind == Can_Id_standard_id_PRESENT) {
    // Standard ID (11 bits)
    frame.can_id = IN_frame->id.u.standard_id;
  } else {
    printf("[vcan] Error: Unknown CAN ID type\n");
    return;
  }

  // Copy data
  frame.len = IN_frame->data.nCount;
  if (frame.len > 8)
    frame.len = 8; // Clamp to max CAN data length

  memcpy(frame.data, IN_frame->data.arr, frame.len);

  int r = write(can_socket, &frame, sizeof(struct can_frame));
  if (r == sizeof(struct can_frame)) {
    printf("[vcan] Frame sent\n");
  } else {
    printf("[vcan] Invalid result [%d] from write\n", r);
  }
}
