/* Body file for function CANopen
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/

#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <time.h>

#include <lely/can/msg.h>
#include <lely/can/net.h>
#include <lely/co/co.h>
#include <lely/co/dev.h>
#include <lely/co/nmt.h>
#include <lely/co/obj.h>
#include <lely/util/cmp.h>
#include <lely/util/memory.h>
#include <lely/util/mempool.h>
#include <lely/util/time.h>

#include "canopen.h"
#include "config.h"
#include "dataview-uniq.h"
#include "lely/co/type.h"
#include "master_dev.h"

#define MEMORY_POOL_SIZE (10 * 1024 * 1024)

static char memory[MEMORY_POOL_SIZE] __attribute__((aligned)) = {0};
static struct mempool memory_pool;
static can_net_t *net = NULL;
static co_dev_t *dev = NULL;
static co_nmt_t *nmt = NULL;
static struct timespec startupTime;

static alloc_t *allocator_init(void) {
  alloc_t *const alloc = mempool_init(&memory_pool, memory, sizeof(memory));
  assert(alloc);
  return alloc;
}

static inline struct timespec convert_asn_time_to_timespec(asn1SccTime time) {
  return (struct timespec){.tv_sec = time.seconds, .tv_nsec = time.nanoseconds};
}

static struct timespec get_current_time() {
  asn1SccTime currentTime;
  canopen_RI_get_elapsed_time(&currentTime);
  return convert_asn_time_to_timespec(currentTime);
}

static struct timespec get_time_from_startup() {
  struct timespec currentTime = get_current_time();
  struct timespec elapsed;

  elapsed.tv_sec = currentTime.tv_sec - startupTime.tv_sec;
  elapsed.tv_nsec = currentTime.tv_nsec - startupTime.tv_nsec;

  // Handle negative nanoseconds
  if (elapsed.tv_nsec < 0) {
    elapsed.tv_sec -= 1;
    elapsed.tv_nsec += 1000000000; // 1 second in nanoseconds
  }

  return elapsed;
}

static int send_callback(const struct can_msg *const msg, uint_least8_t busId,
                         void *userdata) {
  (void)busId;
  (void)userdata;

  if (msg == NULL) {
    return -1;
  }

  // Convert can_msg to Raw_Can_Frame (OCTET STRING)
  asn1SccRaw_Can_Frame frame_data;
  memset(&frame_data, 0, sizeof(frame_data));

  // Encode CAN ID (4 bytes, big-endian)
  uint32_t id = msg->id;
  if (msg->flags & CAN_FLAG_IDE) {
    id |= CAN_FLAG_IDE; // Mark as extended frame
  }

  frame_data.arr[0] = (id >> 24) & 0xFF;
  frame_data.arr[1] = (id >> 16) & 0xFF;
  frame_data.arr[2] = (id >> 8) & 0xFF;
  frame_data.arr[3] = id & 0xFF;

  // Add DLC
  frame_data.arr[4] = msg->len;

  // Add data
  if (msg->len > 0 && msg->len <= 8) {
    memcpy(&frame_data.arr[5], msg->data, msg->len);
  }

  frame_data.nCount = 5 + msg->len;

  // Call TASTE required interface to transmit
  canopen_RI_transmit_data(&frame_data);

  return 0;
}

static asn1SccCANopen_NMT_Command map_nmt_command_to_asn(co_unsigned8_t cs) {
  switch (cs) {
  case CO_NMT_CS_START:
    return asn1SccCANopen_NMT_Command_start;
  case CO_NMT_CS_STOP:
    return asn1SccCANopen_NMT_Command_stop;
  case CO_NMT_CS_ENTER_PREOP:
    return asn1SccCANopen_NMT_Command_enter_preop;
  case CO_NMT_CS_RESET_NODE:
    return asn1SccCANopen_NMT_Command_reset_node;
  case CO_NMT_CS_RESET_COMM:
    return asn1SccCANopen_NMT_Command_reset_comm;
  default:
    printf("[CANopen] Warning: Unknown NMT command: 0x%02x\n", cs);
    return asn1SccCANopen_NMT_Command_start;
  }
}

static asn1SccCANopen_NMT_State map_nmt_state_to_asn(co_unsigned8_t st) {
  // Mask off the toggle bit
  co_unsigned8_t state = st & ~CO_NMT_ST_TOGGLE;

  switch (state) {
  case CO_NMT_ST_BOOTUP:
    return asn1SccCANopen_NMT_State_bootup;
  case CO_NMT_ST_STOP:
    return asn1SccCANopen_NMT_State_stop;
  case CO_NMT_ST_START:
    return asn1SccCANopen_NMT_State_start;
  case CO_NMT_ST_RESET_NODE:
    return asn1SccCANopen_NMT_State_reset_node;
  case CO_NMT_ST_RESET_COMM:
    return asn1SccCANopen_NMT_State_reset_comm;
  case CO_NMT_ST_PREOP:
    return asn1SccCANopen_NMT_State_preop;
  default:
    printf("[CANopen] Warning: Unknown NMT state: 0x%02x\n", st);
    return asn1SccCANopen_NMT_State_bootup;
  }
}

static const char *map_nmt_command_to_string(co_unsigned8_t cs) {
  switch (cs) {
  case CO_NMT_CS_START:
    return "START";
  case CO_NMT_CS_STOP:
    return "STOP";
  case CO_NMT_CS_ENTER_PREOP:
    return "ENTER_PREOP";
  case CO_NMT_CS_RESET_NODE:
    return "RESET_NODE";
  case CO_NMT_CS_RESET_COMM:
    return "RESET_COMM";
  default:
    return "UNKNOWN";
  }
}

static const char *map_nmt_state_to_string(co_unsigned8_t st) {
  // Mask off the toggle bit
  co_unsigned8_t state = st & ~CO_NMT_ST_TOGGLE;

  switch (state) {
  case CO_NMT_ST_BOOTUP:
    return "BOOTUP";
  case CO_NMT_ST_STOP:
    return "STOP";
  case CO_NMT_ST_START:
    return "START";
  case CO_NMT_ST_RESET_NODE:
    return "RESET_NODE";
  case CO_NMT_ST_RESET_COMM:
    return "RESET_COMM";
  case CO_NMT_ST_PREOP:
    return "PREOP";
  default:
    return "UNKNOWN";
  }
}

static void nmt_command_indicator(co_nmt_t *nmt_, co_unsigned8_t cs,
                                  void *data) {
  assert(nmt_ == nmt);
  (void)data;
  printf(
      "[CANopen] NMT command indicator triggered; received command: %x (%s) \n",
      cs, map_nmt_command_to_string(cs));
  const asn1SccCANopen_NMT_Command asnCs = map_nmt_command_to_asn(cs);
  canopen_RI_nmt_command_indicator(&asnCs);
}

static void nmt_state_indicator(co_nmt_t *nmt_, co_unsigned8_t id,
                                co_unsigned8_t st, void *data) {
  assert(nmt_ == nmt);
  (void)data;
  printf("[CANopen] NMT state indicator triggered; ID: %x, state: %x (%s)\n",
         id, st, map_nmt_state_to_string(st));
  const asn1SccCANopen_NMT_State asnSt = map_nmt_state_to_asn(st);
  const asn1SccCANopen_Unsigned8 asnId = id;
  canopen_RI_nmt_state_indicator(&asnId, &asnSt);
}

void canopen_startup(void) {
  // Startup left empty, initialization implemented in canopen_PI_init
}

void canopen_PI_init(void) {
  if (net != NULL) {
    // Already initialized
    printf("[CANopen] Already initialized, ignoring init...\n");
    return;
  }

  printf("[CANopen] Initializing...\n");

  // Initialize device from static object dictionary
  dev = master_dev_init();
  if (dev == NULL) {
    printf("[CANopen] ERROR: Failed to initialize device\n");
    return;
  }

  // Create CAN network
  net = can_net_create(allocator_init(), 0);
  if (net == NULL) {
    printf("[CANopen] ERROR: Failed to create CAN network\n");
    return;
  }

  // Create NMT service
  nmt = co_nmt_create(net, dev);
  if (nmt == NULL) {
    printf("[CANopen] ERROR: Failed to create NMT service\n");
    return;
  }

  // Set network callbacks
  can_net_set_send_func(net, send_callback, NULL);
  co_nmt_set_cs_ind(nmt, &nmt_command_indicator, NULL);
  co_nmt_set_st_ind(nmt, &nmt_state_indicator, NULL);

  startupTime = get_current_time();

  printf("[CANopen] Initialization complete\n");
}

void canopen_PI_canopen_network_tick(void) {
  if (net == NULL) {
    return;
  }

  struct timespec currentTime = get_time_from_startup();
  can_net_set_time(net, &currentTime);

  // TODO: this is debug log, probably kill
  static uint32_t counter = 0;
  if (counter % 100 == 0)
    printf("[CANopen] Current network time: %lds, %ldns\n", currentTime.tv_sec,
           currentTime.tv_nsec);

  counter++;
}

void canopen_PI_change_network_state(const asn1SccCANopen_NMT_State *state) {
  if (net == NULL || nmt == NULL || state == NULL) {
    return;
  }

  // Map ASN.1 NMT state to Lely CANopen NMT command specifier
  co_unsigned8_t cs;
  switch (*state) {
  case CANopen_NMT_State_start:
    cs = CO_NMT_CS_START;
    break;
  case CANopen_NMT_State_stop:
    cs = CO_NMT_CS_STOP;
    break;
  case CANopen_NMT_State_preop:
    cs = CO_NMT_CS_ENTER_PREOP;
    break;
  case CANopen_NMT_State_reset_node:
    cs = CO_NMT_CS_RESET_NODE;
    break;
  case CANopen_NMT_State_reset_comm:
    cs = CO_NMT_CS_RESET_COMM;
    break;
  case CANopen_NMT_State_bootup:
    // Bootup is not a command that can be issued externally
    printf("[CANopen] Warning: Cannot transition to bootup state via "
           "command\n");
    return;
  default:
    printf("[CANopen] Error: Unknown NMT state: %d\n", *state);
    return;
  }

  // Issue the NMT command
  printf("[CANopen] Changing network state to: %d (command: 0x%02X)\n", *state,
         cs);
  int result = co_nmt_cs_ind(nmt, cs);
  if (result != 0) {
    printf("[CANopen] Error: Failed to change network state (error code: %d)\n",
           result);
  }
}

void canopen_PI_issue_network_reset(void) {
  if (nmt == NULL) {
    return;
  }

  // Issue NMT reset node command
  printf("[CANopen] Network reset triggered!\n");
  co_nmt_cs_ind(nmt, CO_NMT_CS_RESET_NODE);
}

void canopen_PI_receive_data(const asn1SccRaw_Can_Frame *frame_data) {
  if (net == NULL || frame_data == NULL) {
    return;
  }

  // Raw-Can-Frame is OCTET STRING (SIZE(4..12))
  // Format: [ID (4 bytes)] [DLC (1 byte optional)] [DATA (0-8 bytes)]
  // Assuming: bytes 0-3 = CAN ID, byte 4 = DLC, bytes 5-12 = data
  // This will probably have to be refactored after restoring translation
  // function.

  struct can_msg frame;
  memset(&frame, 0, sizeof(frame));

  if (frame_data->nCount < 4) {
    printf("[CANopen] ERROR: Invalid frame size %d\n", frame_data->nCount);
    return;
  }

  // Extract CAN ID (assuming 29-bit extended ID in first 4 bytes, big-endian)
  frame.id = ((uint32_t)frame_data->arr[0] << 24) |
             ((uint32_t)frame_data->arr[1] << 16) |
             ((uint32_t)frame_data->arr[2] << 8) |
             ((uint32_t)frame_data->arr[3]);

  // Check if extended frame (bit 3 of ID indicates frame type)
  if (frame.id & CAN_FLAG_IDE) {
    frame.flags = CAN_FLAG_IDE;
    frame.id &= CAN_MASK_EID; // 29-bit mask
  } else {
    frame.flags = 0;
    frame.id &= CAN_MASK_BID; // 11-bit mask
  }

  // Extract data length and data
  if (frame_data->nCount > 4) {
    frame.len = frame_data->arr[4];
    if (frame.len > 8) {
      frame.len = 8;
    }

    int data_bytes = frame_data->nCount - 5;
    if (data_bytes > frame.len) {
      data_bytes = frame.len;
    }

    if (data_bytes > 0) {
      memcpy(frame.data, &frame_data->arr[5], data_bytes);
    }
  } else {
    frame.len = 0;
  }

  // Pass frame to CAN network
  can_net_recv(net, &frame, 0);
}

void canopen_PI_set_object_dictionary_data(
    const asn1SccCANopen_Object_Index *index,
    const asn1SccCANopen_Subobject_Index *subindex,
    const asn1SccCANopen_Value *value) {
  if (dev == NULL || index == NULL || subindex == NULL || value == NULL) {
    return;
  }

  co_obj_t *obj = co_dev_find_obj(dev, (co_unsigned16_t)(*index));
  if (obj == NULL) {
    printf("[CANopen] ERROR: Object %04lX not found\n", *index);
    return;
  }

  co_sub_t *sub = co_obj_find_sub(obj, (co_unsigned8_t)(*subindex));
  if (sub == NULL) {
    printf("[CANopen] ERROR: Sub-object %04lX:%02lX not found\n", *index,
           *subindex);
    return;
  }

  // Write value based on the choice type
  switch (value->kind) {
  case CANopen_Value_boolean_d_PRESENT:
    co_sub_set_val_b(sub, value->u.boolean_d);
    break;
  case CANopen_Value_unsigned8_PRESENT:
    co_sub_set_val_u8(sub, (co_unsigned8_t)value->u.unsigned8);
    break;
  case CANopen_Value_unsigned16_PRESENT:
    co_sub_set_val_u16(sub, (co_unsigned16_t)value->u.unsigned16);
    break;
  case CANopen_Value_unsigned32_PRESENT:
    co_sub_set_val_u32(sub, (co_unsigned32_t)value->u.unsigned32);
    break;
  case CANopen_Value_signed8_PRESENT:
    co_sub_set_val_i8(sub, (co_integer8_t)value->u.signed8);
    break;
  case CANopen_Value_signed16_PRESENT:
    co_sub_set_val_i16(sub, (co_integer16_t)value->u.signed16);
    break;
  case CANopen_Value_signed32_PRESENT:
    co_sub_set_val_i32(sub, (co_integer32_t)value->u.signed32);
    break;
  case CANopen_Value_real32_PRESENT:
    co_sub_set_val_r32(sub, (co_real32_t)value->u.real32);
    break;
  default:
    printf("[CANopen] ERROR: Unsupported value type 0x%04X\n", value->kind);
    return;
  }

  printf("[CANopen] Set OD %04lX:%02lX\n", *index, *subindex);
}

void canopen_PI_get_object_dictionary_data(
    const asn1SccCANopen_Object_Index *index,
    const asn1SccCANopen_Subobject_Index *subindex,
    asn1SccCANopen_Value *value) {
  if (dev == NULL || index == NULL || subindex == NULL || value == NULL) {
    return;
  }

  co_obj_t *obj = co_dev_find_obj(dev, (co_unsigned16_t)(*index));
  if (obj == NULL) {
    printf("[CANopen] ERROR: Object %04lX not found\n", *index);
    return;
  }

  co_sub_t *sub = co_obj_find_sub(obj, (co_unsigned8_t)(*subindex));
  if (sub == NULL) {
    printf("[CANopen] ERROR: Sub-object %04lX:%02lX not found\n", *index,
           *subindex);
    return;
  }

  // Read value based on the object dictionary data type
  co_unsigned16_t type = co_sub_get_type(sub);

  switch (type) {
  case CO_DEFTYPE_BOOLEAN:
    value->kind = CANopen_Value_boolean_d_PRESENT;
    value->u.boolean_d = (co_sub_get_val_b(sub));
    break;
  case CO_DEFTYPE_UNSIGNED8:
    value->kind = CANopen_Value_unsigned8_PRESENT;
    value->u.unsigned8 = co_sub_get_val_u8(sub);
    break;
  case CO_DEFTYPE_UNSIGNED16:
    value->kind = CANopen_Value_unsigned16_PRESENT;
    value->u.unsigned16 = co_sub_get_val_u16(sub);
    break;
  case CO_DEFTYPE_UNSIGNED32:
    value->kind = CANopen_Value_unsigned32_PRESENT;
    value->u.unsigned32 = co_sub_get_val_u32(sub);
    break;
  case CO_DEFTYPE_INTEGER8:
    value->kind = CANopen_Value_signed8_PRESENT;
    value->u.signed16 = co_sub_get_val_i8(sub);
    break;
  case CO_DEFTYPE_INTEGER16:
    value->kind = CANopen_Value_signed16_PRESENT;
    value->u.signed16 = co_sub_get_val_i16(sub);
    break;
  case CO_DEFTYPE_INTEGER32:
    value->kind = CANopen_Value_signed32_PRESENT;
    value->u.signed32 = co_sub_get_val_i32(sub);
    break;
  case CO_DEFTYPE_REAL32:
    value->kind = CANopen_Value_real32_PRESENT;
    value->u.real32 = co_sub_get_val_r32(sub);
    break;
  default:
    printf("[CANopen] ERROR: Unsupported value type 0x%04X\n", type);
    break;
  }

  printf("[CANopen] Get OD %04lX:%02lX\n", *index, *subindex);
}
