/* Header file for function CANopen
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void canopen_startup(void);

/* Provided interfaces */
void canopen_PI_canopen_network_tick( void );


void canopen_PI_change_node_state( const asn1SccCANopen_NMT_State * );


void canopen_PI_get_object_dictionary_data( const asn1SccCANopen_Object_Index *, const asn1SccCANopen_Subobject_Index *, asn1SccCANopen_Value * );


void canopen_PI_init( void );


void canopen_PI_issue_slave_command( const asn1SccCANopen_NodeID *, const asn1SccCANopen_NMT_Command * );


void canopen_PI_receive_data( const asn1SccCan_Frame * );


void canopen_PI_reset_node( void );


void canopen_PI_set_object_dictionary_data( const asn1SccCANopen_Object_Index *, const asn1SccCANopen_Subobject_Index *, const asn1SccCANopen_Value * );

/* Required interfaces */
extern void canopen_RI_get_elapsed_time( asn1SccTime * );


extern void canopen_RI_nmt_command_indicator( const asn1SccCANopen_NMT_Command * );


extern void canopen_RI_nmt_heartbeat_indicator( const asn1SccCANopen_NodeID *, const asn1SccCANopen_NMT_HeartbeatState *, const asn1SccCANopen_NMT_HeartbeatReason * );


extern void canopen_RI_nmt_state_indicator( const asn1SccCANopen_Unsigned8 *, const asn1SccCANopen_NMT_State * );


extern void canopen_RI_nmt_sync_indicator( const asn1SccCANopen_Unsigned8 * );


extern void canopen_RI_transmit_data( const asn1SccCan_Frame * );


#ifdef __cplusplus
}
#endif
