/* Body file for function CANopen_processor
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#define LELY_NO_MALLOC 1
#define LELY_NO_CO_OBJ_NAME 1
#include "canopen_processor.h"
#include <stdio.h>
#include <string.h>
#include <assert.h>

#include <lely/co/co.h>
#include <lely/co/dev.h>
#include <lely/co/nmt.h>
#include <lely/can/net.h>

#include <lely/util/memory.h>
#include <lely/util/mempool.h>
#include <lely/util/cmp.h>



#include "master_dev.h"

#define MEMORY_POOL_SIZE (10 * 1024 * 1024)

static char memory[MEMORY_POOL_SIZE] __attribute__((aligned)) = {0};
static struct mempool memory_pool;

static alloc_t* allocator_init(void)
{
    alloc_t *const alloc = mempool_init(&memory_pool, memory, sizeof(memory));
    assert(alloc);
    return alloc;
}

static size_t allocator_used_memory(void)
{
    return mem_size(&memory_pool.vtbl);
}

static int
send_callback(const struct can_msg *const msg, uint_least8_t busId, void *userdata)
{
    static asn1SccCan_Frame param;

    param.id.id.kind = Can_Id_standard_id_PRESENT;
    param.id.id.u.standard_id = msg->id;
    param.data.nCount=(int)msg->len;
    memcpy(param.data.arr, msg->data, 8);

    canopen_processor_RI_send_data(&param);

    return 0;
}

static can_net_t* net = NULL;
static co_dev_t* dev = NULL;
static co_nmt_t* nmt = NULL;


// ======== PUBLIC FUNCTIONS ========

void canopen_processor_startup(void)
{
    // startup left empty, initialization implemented in canopen_processor_PI_init
    printf("Pointer is %llx\n", &uint8_cmp);
    printf("Inside structure it is %ullx\n", master_dev_1000.tree.cmp);
}

void canopen_processor_PI_canopen_network_tick(void)
{
    if(net == NULL)
    {
        return;
    }
}


void canopen_processor_PI_change_network_state(void)
{
    if(net == NULL)
    {
        return;
    }
}


void canopen_processor_PI_get_data_from_object_dictionary
      (const asn1SccCANopen_Object_Index *IN_object,
       const asn1SccCANopen_Subobject_Index *IN_subobject,
       asn1SccCANopen_Value *OUT_value)

{
    if(net == NULL)
    {
        return;
    }
}


void canopen_processor_PI_init(void)
{
    printf("CANopen issue init\n");
    if(net != NULL) {
        return;
    }
    printf("CANopen init\n");
        dev = master_dev_init();
    net = can_net_create(allocator_init(), 0);
    can_net_set_send_func(net, send_callback, NULL);

    nmt = co_nmt_create(net, dev);
}


void canopen_processor_PI_issue_network_reset(void)
{
    if(net == NULL)
    {
        return;
    }
}


void canopen_processor_PI_receive_data
      (const asn1SccCan_Frame *IN_frame)

{
    if(net == NULL)
    {
        return;
    }
    printf("CANopen receive_data\n");
    static struct can_msg frame;
    frame.id = IN_frame->id.id.u.standard_id;
    frame.flags = 0;
    frame.len = IN_frame->data.nCount;
    memcpy(frame.data, IN_frame->data.arr, 8);
    can_net_recv(net, &frame, 0);
}


void canopen_processor_PI_set_data_in_object_dictionary
      (const asn1SccCANopen_Object_Index *IN_object,
       const asn1SccCANopen_Subobject_Index *IN_subobject,
       const asn1SccCANopen_Value *IN_value)

{
    if(net == NULL)
    {
        return;
    }
}


