/* Body file for function helper
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "helper.h"
#include <stdio.h>

static asn1SccOperation_Result result;

void helper_startup(void)
{
   result.id=0;
   result.exist.result_value = 0;
}

void helper_PI_do_change_network_state(void)
{
   printf("helper - forward change_network_state\n");
   helper_RI_change_network_state();

   result.id=result.id+1;
   result.exist.result_value = 0;
   helper_RI_result(&result);
}

void helper_PI_do_get_data
      (const asn1SccGet_Data_Request *IN_param)

{
    printf("helper - forward get_data_from_object_dictionary\n");
    asn1SccCANopen_Value result_value;
    helper_RI_get_data_from_object_dictionary(&IN_param->object, &IN_param->subobject, &result_value);

    result.id=result.id+1;
    result.exist.result_value = 1;
    result.result_value = result_value;
    helper_RI_result(&result);
}

void helper_PI_do_init(void)
{
    printf("helper - forward init\n");
    helper_RI_init();

    result.id=result.id+1;
    result.exist.result_value = 0;
    helper_RI_result(&result);
}

void helper_PI_do_issue_network_reset(void)
{
    printf("helper - forward issue_network_reset\n");
    helper_RI_issue_network_reset();

    result.id=result.id+1;
    result.exist.result_value = 0;
    helper_RI_result(&result);
}

void helper_PI_do_set_data
      (const asn1SccSet_Data_Request *IN_param)

{
   printf("helper - forward set_data_in_object_dictionary\n");
   helper_RI_set_data_in_object_dictionary(&IN_param->object, &IN_param->subobject, &IN_param->data_value);

   result.id=result.id+1;
   result.exist.result_value = 0;
   helper_RI_result(&result);
}
