/* Body file for function helper
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "helper.h"
#include <stdio.h>

void helper_startup(void) {
  // Write your initialisation code
  // You may call sporadic required interfaces and start timers
  // puts ("[helper] Startup");
}

void helper_PI_do_init(void) { helper_RI_init(); }

void helper_PI_do_reset(void) { helper_RI_issue_network_reset(); }
