/* Body file for function time_provider
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "time_provider.h"
#include <bits/time.h>
#include <time.h>
// #include <stdio.h>

void time_provider_startup(void) {
  // Write your initialisation code
  // You may call sporadic required interfaces and start timers
  // puts ("[time_provider] Startup");
}

void time_provider_PI_get_elapsed_time(asn1SccTime *OUT_time) {
  struct timespec time;
  if (clock_gettime(CLOCK_MONOTONIC, &time) == 0) {
    OUT_time->seconds = time.tv_sec;
    OUT_time->nanoseconds = time.tv_nsec;
  } else {
    OUT_time->seconds = 0;
    OUT_time->nanoseconds = 0;
    printf("[time_provider] ERROR: could not fetch current system time, "
           "rolling back to 0!\n");
  }
}
