/* Body file for function control
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "control.h"
#include <stdbool.h>
#include <stdio.h>

void control_startup(void) {
  // Write your initialisation code
  // You may call sporadic required interfaces and start timers
  // puts ("[control] Startup");
}

void control_PI_trigger(void) {
  static uint32_t ticks = 0;
  static bool initTriggered = false;
  static bool networkResetTriggered = false;

  if (!initTriggered) {
    printf("[helper] Triggering initialization...\n");
    control_RI_do_init();
    initTriggered = true;
  }

  if (ticks == 1 && !networkResetTriggered) {
    printf("[helper] Triggering network reset...\n");
    control_RI_do_reset();
    networkResetTriggered = true;
  }

  ticks++;
}
